name: Deploy to Windows Prod

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  windows-deploy:
    runs-on: windows-latest
    env:
      DB_HOST: ${{ secrets.PROD_DB_HOST }}
      DB_PW: ${{ secrets.PROD_DB_PW}}
      DB_USER: ${{ secrets.PROD_DB_USER }}
      DB_NAME: ${{ secrets.PROD_DB_NAME }}
      TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
      TWILIO_AUTH_TOKEN1: ${{secrets.TWILIO_AUTH_TOKEN2}}
      TWILIO_AUTH_TOKEN2: ${{secrets.TWILIO_AUTH_TOKEN2}}
      TWILIO_NUMBER: ${{secrets.TWILIO_NUMBER}}
      VUE_APP_CLIENT_ID: ${{secrets.VUE_APP_CLIENT_ID}}
      VUE_APP_API_URL: ${{secrets.VUE_APP_API_URL}}
      VUE_APP_CLIENT_URL: https://tutorscheduling.oc.edu
      VUE_APP_SITE_URL: https://tutorscheduling.oc.edu
      GOOGLE_AUDIENCE: ${{secrets.GOOGLE_AUDIENCE}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/
          remote: c:/Apache24/htdocs/tutorscheduling
          recursive: true
          host: "tutorscheduling.oc.edu"
          username: "david.north"
          privateKey: ${{ secrets.PROD_WIN_SERVER_SSH_KEY  }}
